

export const HERO_CONTENT = `I am a passionate front-end developer with strong expertise in React.js and Tailwind CSS. I have a solid foundation in HTML, CSS, and JavaScript, Bootstrap, and I specialize in building dynamic and responsive user interfaces. Additionally, I am proficient in C, C++, and Python, which complements my development skills. As a graphic designer, I also bring experience in creating visually appealing designs. My goal is to integrate these skills to deliver exceptional user experiences and innovative web applications.`;
export const PRO_1 = `I am a passionate front-end developer with strong expertise in React.js and Tailwind CSS. I have a solid foundation in HTML, CSS, and JavaScript, Bootstrap, and I specialize in building dynamic and responsive user interfaces. Additionally, I am proficient in C, C++, and Python, which complements my development skills. As a graphic designer, I also bring experience in creating visually appealing designs. My goal is to integrate these skills to deliver exceptional user experiences and innovative web applications.`;
export const PRO_2 = `I am a passionate front-end developer with strong expertise in React.js and Tailwind CSS. I have a solid foundation in HTML, CSS, and JavaScript, Bootstrap, and I specialize in building dynamic and responsive user interfaces. Additionally, I am proficient in C, C++, and Python, which complements my development skills. As a graphic designer, I also bring experience in creating visually appealing designs. My goal is to integrate these skills to deliver exceptional user experiences and innovative web applications.`;
export const PRO_3 = `I am a passionate front-end developer with strong expertise in React.js and Tailwind CSS. I have a solid foundation in HTML, CSS, and JavaScript, Bootstrap, and I specialize in building dynamic and responsive user interfaces. Additionally, I am proficient in C, C++, and Python, which complements my development skills. As a graphic designer, I also bring experience in creating visually appealing designs. My goal is to integrate these skills to deliver exceptional user experiences and innovative web applications.`;
export const PRO_4 = `I am a passionate front-end developer with strong expertise in React.js and Tailwind CSS. I have a solid foundation in HTML, CSS, and JavaScript, Bootstrap, and I specialize in building dynamic and responsive user interfaces. Additionally, I am proficient in C, C++, and Python, which complements my development skills. As a graphic designer, I also bring experience in creating visually appealing designs. My goal is to integrate these skills to deliver exceptional user experiences and innovative web applications.`;

export const ABOUT_TEXT = `I am a front-end developer with a deep passion for creating engaging and responsive web interfaces. My expertise lies in React.js and Tailwind CSS, and I have a strong foundation in HTML, CSS, and JavaScript. Beyond development, I am skilled in C, C++, and Python, which enhances my problem-solving capabilities. In addition to my technical skills, I am a graphic designer with a keen eye for visual aesthetics. My goal is to blend these diverse skills to craft exceptional user experiences and innovative web applications. Outside of my professional life, I enjoy playing musical instruments, including the guitar and flute. I also find joy in sketching and portrait art, which allows me to express my creativity in different ways.`;




